/**
 * Simple ESM build shim: copies dist/*.js to dist/*.mjs with
 * CJS-to-ESM headers so bundlers can use the module export paths.
 * A full bundler (tsup/rollup) would be better for production — this shim
 * keeps the package zero-devDep for initial rollout.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = join(__dirname, '..', 'dist')

// ---- index.mjs ----
const indexCjs = join(distDir, 'index.js')
const indexEsm = join(distDir, 'index.mjs')

if (!existsSync(indexCjs)) {
  console.error('dist/index.js not found — run tsc first')
  process.exit(1)
}

const indexEsmContent = `// ESM wrapper generated by build-esm.mjs
import { createRequire } from 'module'
const _require = createRequire(import.meta.url)
const _mod = _require('./index.js')
export default _mod.default ?? _mod
export const {
  nSelfPalette,
  brandCssVars,
  brandUtilities,
  HEX_ALLOWLIST,
  PAGE_BG_DARK,
  statusTones,
  pillTones,
  spacingTokens,
  radiusTokens,
} = _mod
`

writeFileSync(indexEsm, indexEsmContent)
console.log('dist/index.mjs written')

// ---- tailwind-plugin.mjs ----
const pluginCjs = join(distDir, 'tailwind-plugin.js')
const pluginEsm = join(distDir, 'tailwind-plugin.mjs')

if (!existsSync(pluginCjs)) {
  console.error('dist/tailwind-plugin.js not found — run tsc first')
  process.exit(1)
}

const pluginEsmContent = `// ESM wrapper generated by build-esm.mjs
import { createRequire } from 'module'
const _require = createRequire(import.meta.url)
const _mod = _require('./tailwind-plugin.js')
export default _mod.default ?? _mod
export const {
  themeColors,
  themeSpacing,
  themeBorderRadius,
  themeExtend,
  nSelfPalette,
  brandCssVars,
  brandUtilities,
  PAGE_BG_DARK,
  statusTones,
  pillTones,
  spacingTokens,
  radiusTokens,
} = _mod
`

writeFileSync(pluginEsm, pluginEsmContent)
console.log('dist/tailwind-plugin.mjs written')
