/**
 * @nself/native-bridge — NclawModule iOS Objective-C++ implementation.
 *
 * Purpose: Bridges libnclaw Rust C-ABI functions to React Native JSI via
 *          react-native-nitro-modules on iOS. Implements every FFI symbol
 *          from FFI audit §5 Groups A–D.
 *
 * Inputs:  libnclaw.h (cbindgen-generated from nclaw/core/src/lib.rs)
 *          ios/libs/libnclaw.a (Rust static library — built by scripts/build.sh)
 *
 * Outputs: NclawModule registered NitroModule ("NclawModule").
 *
 * Thread model:
 *   - _ffiQueue: private serial dispatch_queue_t — all Rust FFI calls run here.
 *   - JS calls arrive on JS thread → async_dispatch to _ffiQueue → resolve/reject.
 *   - libnclaw_last_error() called on _ffiQueue immediately after failing call.
 *   - Battery + thermal monitoring on main thread → dispatches setters to _ffiQueue.
 *
 * Memory rules (RF-01, §3):
 *   - *const c_char returns (libnclaw_last_error, libnclaw_version): copy to
 *     NSString immediately. DO NOT free — static/thread-local lifetime.
 *   - *mut c_char returns (keypair_public_b64, cipher_encrypt, cipher_decrypt):
 *     copy to NSString, then call libnclaw_free_string immediately.
 *   - *mut FfiDeviceKeypair, *mut FfiSessionCipher: wrapped in NativeState.
 *     NativeState destructor calls libnclaw_keypair_free / libnclaw_cipher_free.
 *
 * Cross-ref: T-P3-E4-W1-S1-T02 (FFI audit — memory rules in §3)
 *            ios/libs/nclaw.h (cbindgen-generated)
 *            scripts/build.sh (cross-compile script)
 */

#import "NclawModule.h"

// cbindgen-generated C header for nclaw/core.
// Generated by: cbindgen --config nclaw/core/cbindgen.toml --output ios/libs/nclaw.h
// Located at: packages/native-bridge/ios/libs/nclaw.h (produced by build.sh).
#include "libs/nclaw.h"

#import <UIKit/UIKit.h>

// ---------------------------------------------------------------------------
// NativeState wrappers for opaque Rust handles
// ---------------------------------------------------------------------------

/**
 * NativeDeviceKeypairState — wraps FfiDeviceKeypair* for NativeState lifecycle.
 *
 * Destructor calls libnclaw_keypair_free to release Rust-allocated memory.
 * JS GC → ObjC dealloc → libnclaw_keypair_free — no manual free needed in JS.
 */
@interface NativeDeviceKeypairState : NSObject
@property (nonatomic, readonly) FfiDeviceKeypair *keypair;
- (instancetype)initWithKeypair:(FfiDeviceKeypair *)keypair;
@end

@implementation NativeDeviceKeypairState

- (instancetype)initWithKeypair:(FfiDeviceKeypair *)keypair {
    if ((self = [super init])) {
        _keypair = keypair;
    }
    return self;
}

- (void)dealloc {
    if (_keypair != NULL) {
        libnclaw_keypair_free(_keypair);
        _keypair = NULL;
    }
}

@end

/**
 * NativeSessionCipherState — wraps FfiSessionCipher* for NativeState lifecycle.
 *
 * Destructor calls libnclaw_cipher_free to release Rust-allocated memory.
 */
@interface NativeSessionCipherState : NSObject
@property (nonatomic, readonly) FfiSessionCipher *cipher;
- (instancetype)initWithCipher:(FfiSessionCipher *)cipher;
@end

@implementation NativeSessionCipherState

- (instancetype)initWithCipher:(FfiSessionCipher *)cipher {
    if ((self = [super init])) {
        _cipher = cipher;
    }
    return self;
}

- (void)dealloc {
    if (_cipher != NULL) {
        libnclaw_cipher_free(_cipher);
        _cipher = NULL;
    }
}

@end

// ---------------------------------------------------------------------------
// Error domain + helpers
// ---------------------------------------------------------------------------

static NSString *const kNclawErrorDomain = @"com.nself.nclaw";

/**
 * Capture the current libnclaw thread-local error string as an NSError.
 *
 * MUST be called on _ffiQueue immediately after a failing FFI call.
 * libnclaw_last_error() is thread-local — calling from any other thread
 * returns NULL (RF-01 from FFI audit §7).
 */
static NSError *nclawCaptureError(NSString *fallback) {
    const char *raw = libnclaw_last_error();
    NSString *msg = (raw != NULL)
        ? [NSString stringWithUTF8String:raw]  // thread-local — no free needed
        : fallback;
    return [NSError errorWithDomain:kNclawErrorDomain
                               code:-1
                           userInfo:@{NSLocalizedDescriptionKey: msg}];
}

// ---------------------------------------------------------------------------
// NclawModule implementation
// ---------------------------------------------------------------------------

@implementation NclawModule {
    dispatch_queue_t _ffiQueue;
    id<NSObject> _batteryObserver;
    id<NSObject> _thermalObserver;
}

- (instancetype)init {
    if ((self = [super init])) {
        _ffiQueue = dispatch_queue_create(
            "com.nself.nclaw.ffi",
            DISPATCH_QUEUE_SERIAL
        );
        [self _startPlatformMonitoring];
    }
    return self;
}

- (void)dealloc {
    [self _stopPlatformMonitoring];
}

// ---------------------------------------------------------------------------
// Platform monitoring (battery + thermal → damper setters)
// ---------------------------------------------------------------------------

- (void)_startPlatformMonitoring {
    // Enable battery monitoring for UIDevice.batteryLevel (RF-06).
    [UIDevice currentDevice].batteryMonitoringEnabled = YES;

    __weak NclawModule *weakSelf = self;

    _batteryObserver = [[NSNotificationCenter defaultCenter]
        addObserverForName:UIDeviceBatteryLevelDidChangeNotification
                    object:nil
                     queue:[NSOperationQueue mainQueue]
                usingBlock:^(NSNotification *note) {
        float level = [UIDevice currentDevice].batteryLevel;
        if (level >= 0) {
            uint8_t pct = (uint8_t)(level * 100.0f);
            [weakSelf setBatteryPct:pct];
        }
    }];

    _thermalObserver = [[NSNotificationCenter defaultCenter]
        addObserverForName:NSProcessInfoThermalStateDidChangeNotification
                    object:nil
                     queue:[NSOperationQueue mainQueue]
                usingBlock:^(NSNotification *note) {
        NSProcessInfoThermalState state = [NSProcessInfo processInfo].thermalState;
        uint8_t level = 0;
        switch (state) {
            case NSProcessInfoThermalStateNominal:  level = 0; break;
            case NSProcessInfoThermalStateFair:     level = 1; break;
            case NSProcessInfoThermalStateSerious:  level = 2; break;
            case NSProcessInfoThermalStateCritical: level = 3; break;
        }
        [weakSelf setThermalLevel:level];
    }];
}

- (void)_stopPlatformMonitoring {
    if (_batteryObserver) {
        [[NSNotificationCenter defaultCenter] removeObserver:_batteryObserver];
    }
    if (_thermalObserver) {
        [[NSNotificationCenter defaultCenter] removeObserver:_thermalObserver];
    }
    [UIDevice currentDevice].batteryMonitoringEnabled = NO;
}

// ---------------------------------------------------------------------------
// Group A — Crypto (lib.rs symbols 2–9)
// ---------------------------------------------------------------------------

- (NSString *)getVersion {
    // libnclaw_version → *const c_char (static — DO NOT free).
    const char *raw = libnclaw_version();
    return (raw != NULL) ? [NSString stringWithUTF8String:raw] : @"unknown";
}

- (nullable NativeDeviceKeypairState *)keypairGenerate:(NSError **)error {
    __block FfiDeviceKeypair *kp = NULL;
    dispatch_sync(_ffiQueue, ^{
        kp = libnclaw_keypair_generate();
    });
    if (kp == NULL) {
        __block NSError *capturedError = nil;
        dispatch_sync(_ffiQueue, ^{
            capturedError = nclawCaptureError(@"keypairGenerate failed");
        });
        if (error) *error = capturedError;
        return nil;
    }
    return [[NativeDeviceKeypairState alloc] initWithKeypair:kp];
}

- (nullable NSString *)keypairPublicB64:(NativeDeviceKeypairState *)kp
                                   error:(NSError **)error {
    __block char *raw = NULL;
    dispatch_sync(_ffiQueue, ^{
        raw = libnclaw_keypair_public_b64(kp.keypair);
    });
    if (raw == NULL) {
        __block NSError *capturedError = nil;
        dispatch_sync(_ffiQueue, ^{
            capturedError = nclawCaptureError(@"keypairPublicB64 failed");
        });
        if (error) *error = capturedError;
        return nil;
    }
    // Copy caller-owned string to NSString, then free Rust allocation.
    NSString *result = [NSString stringWithUTF8String:raw];
    libnclaw_free_string(raw);
    return result;
}

- (nullable NativeSessionCipherState *)keypairDh:(NativeDeviceKeypairState *)kp
                                      remotePubB64:(NSString *)remotePubB64
                                             error:(NSError **)error {
    const char *remoteCStr = [remotePubB64 UTF8String];
    __block FfiSessionCipher *cipher = NULL;
    dispatch_sync(_ffiQueue, ^{
        cipher = libnclaw_keypair_dh(kp.keypair, remoteCStr);
    });
    if (cipher == NULL) {
        __block NSError *capturedError = nil;
        dispatch_sync(_ffiQueue, ^{
            capturedError = nclawCaptureError(@"keypairDh failed — check remotePubB64 base64 format");
        });
        if (error) *error = capturedError;
        return nil;
    }
    return [[NativeSessionCipherState alloc] initWithCipher:cipher];
}

- (nullable NSString *)cipherEncrypt:(NativeSessionCipherState *)cipher
                              plaintext:(NSString *)plaintext
                                  error:(NSError **)error {
    const char *plainCStr = [plaintext UTF8String];
    __block char *raw = NULL;
    dispatch_sync(_ffiQueue, ^{
        raw = libnclaw_cipher_encrypt(cipher.cipher, plainCStr);
    });
    if (raw == NULL) {
        __block NSError *capturedError = nil;
        dispatch_sync(_ffiQueue, ^{
            capturedError = nclawCaptureError(@"cipherEncrypt failed");
        });
        if (error) *error = capturedError;
        return nil;
    }
    NSString *result = [NSString stringWithUTF8String:raw];
    libnclaw_free_string(raw);
    return result;
}

- (nullable NSString *)cipherDecrypt:(NativeSessionCipherState *)cipher
                                  wire:(NSString *)wire
                                 error:(NSError **)error {
    const char *wireCStr = [wire UTF8String];
    __block char *raw = NULL;
    dispatch_sync(_ffiQueue, ^{
        raw = libnclaw_cipher_decrypt(cipher.cipher, wireCStr);
    });
    if (raw == NULL) {
        __block NSError *capturedError = nil;
        dispatch_sync(_ffiQueue, ^{
            capturedError = nclawCaptureError(@"cipherDecrypt failed — MAC mismatch or corrupt wire format");
        });
        if (error) *error = capturedError;
        return nil;
    }
    NSString *result = [NSString stringWithUTF8String:raw];
    libnclaw_free_string(raw);
    return result;
}

// ---------------------------------------------------------------------------
// Group B — Platform dampers (mobile_ffi.rs symbols 11–13)
// ---------------------------------------------------------------------------

- (void)setLowPower:(BOOL)flag {
    dispatch_async(_ffiQueue, ^{
        nclaw_set_low_power((bool)flag);
    });
}

- (void)setBatteryPct:(uint8_t)pct {
    // Clamp to [0, 100] — JS number coercion may send out-of-range values.
    uint8_t clamped = (pct > 100) ? 100 : pct;
    dispatch_async(_ffiQueue, ^{
        nclaw_set_battery_pct(clamped);
    });
}

- (void)setThermalLevel:(uint8_t)level {
    // Clamp to [0, 3] — matches NSProcessInfoThermalState range.
    uint8_t clamped = (level > 3) ? 3 : level;
    dispatch_async(_ffiQueue, ^{
        nclaw_set_thermal_level(clamped);
    });
}

// ---------------------------------------------------------------------------
// Group C — frb-ported core (api.rs symbols 14–16)
// ---------------------------------------------------------------------------

- (NSString *)nclawVersion {
    // frb symbol 14: nclaw_version() → String (static string, no free).
    const char *raw = nclaw_version();
    return (raw != NULL) ? [NSString stringWithUTF8String:raw] : @"unknown";
}

- (NSString *)probeDevice {
    // frb symbol 15: probe_device() → JSON String.
    char *raw = NULL;
    dispatch_sync(_ffiQueue, ^{
        raw = probe_device();
    });
    if (raw == NULL) return @"{}";
    NSString *result = [NSString stringWithUTF8String:raw];
    libnclaw_free_string(raw);
    return result ?: @"{}";
}

- (NSString *)classifyTierWithProbeJson:(NSString *)probeJson
                                  allowT4:(BOOL)allowT4 {
    // frb symbol 16: classify_tier(probe_json, allow_t4) → JSON String.
    const char *probeCStr = [probeJson UTF8String];
    __block char *raw = NULL;
    dispatch_sync(_ffiQueue, ^{
        raw = classify_tier(probeCStr, (bool)allowT4);
    });
    if (raw == NULL) return @"{}";
    NSString *result = [NSString stringWithUTF8String:raw];
    libnclaw_free_string(raw);
    return result ?: @"{}";
}

// ---------------------------------------------------------------------------
// Primary chat + memory surface
//
// These convenience methods delegate to the Rust core's chat + memory pipeline.
// All run on _ffiQueue; resolve/reject blocks are called from _ffiQueue.
// nclaw/mobile's NitroModules glue lifts these into JS Promise<T>.
// ---------------------------------------------------------------------------

- (void)chatSend:(NSString *)message
          resolve:(void (^)(NSString *response))resolve
           reject:(void (^)(NSError *error))reject {
    const char *msgCStr = [message UTF8String];
    dispatch_async(_ffiQueue, ^{
        char *raw = nclaw_chat_send(msgCStr);
        if (raw == NULL) {
            NSError *err = nclawCaptureError(@"chatSend failed");
            reject(err);
            return;
        }
        NSString *response = [NSString stringWithUTF8String:raw];
        libnclaw_free_string(raw);
        resolve(response ?: @"");
    });
}

- (void)memorySearch:(NSString *)query
               limit:(NSInteger)limit
             resolve:(void (^)(NSString *json))resolve
              reject:(void (^)(NSError *error))reject {
    const char *queryCStr = [query UTF8String];
    int32_t limitI32 = (int32_t)MAX(0, MIN(limit, INT32_MAX));
    dispatch_async(_ffiQueue, ^{
        char *raw = nclaw_memory_search(queryCStr, limitI32);
        if (raw == NULL) {
            NSError *err = nclawCaptureError(@"memorySearch failed");
            reject(err);
            return;
        }
        NSString *json = [NSString stringWithUTF8String:raw];
        libnclaw_free_string(raw);
        resolve(json ?: @"[]");
    });
}

- (void)memoryInsert:(NSString *)messageJson
             resolve:(void (^)(void))resolve
              reject:(void (^)(NSError *error))reject {
    const char *jsonCStr = [messageJson UTF8String];
    dispatch_async(_ffiQueue, ^{
        bool ok = nclaw_memory_insert(jsonCStr);
        if (!ok) {
            NSError *err = nclawCaptureError(@"memoryInsert failed");
            reject(err);
            return;
        }
        resolve();
    });
}

- (void)memoryReplaceId:(NSString *)memId
             messageJson:(NSString *)messageJson
                 resolve:(void (^)(void))resolve
                  reject:(void (^)(NSError *error))reject {
    const char *idCStr = [memId UTF8String];
    const char *jsonCStr = [messageJson UTF8String];
    dispatch_async(_ffiQueue, ^{
        bool ok = nclaw_memory_replace(idCStr, jsonCStr);
        if (!ok) {
            NSError *err = nclawCaptureError(@"memoryReplace failed");
            reject(err);
            return;
        }
        resolve();
    });
}

@end
